config/routes.rb
require 'api_constraints'

Mybusa::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :opportunities, :only => [:index, :show]
  get 'find-opportunities', to: 'opportunities#index', as: :find_opportunities

  resources :sbir_solicitations do
    get 'prepopulate', to: 'sbir_solicitations#prepopulate', as: :prepopulate
  end

  resource :profile do
    resources :profile_people, as: 'people'
  end

  resources :sbir_apps

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # API
  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
    	get '/index' => 'base#index'
      resources :profiles
    end
  end
end

app/controllers/sbir_apps_controller.rb
class SbirAppsController < ApplicationController
  def new
    @form = MYUSA_FORMS['SF-424']
    gon.myusa_form_tooltips = @form['form_fields'].map{|x| x['name']}
  end
end

app/helpers/sbir_apps_helper.rb
module SbirAppsHelper
  def form_title(form)
    "#{form['title']} (#{form['number']})"
  end

  def form_input(f, form_field)
    f.input form_field['name'],
      as: formtastic_field_type(form_field),
      collection: form_field['options'],
      hint: form_field['description'],
      title: form_field['label'],
      label: form_field['label'] || form_field['name'].humanize,
      required: form_field['is_required']
  end

  def omb_info(form)
    link_to "Form Approved OMB##{form['omb_control_number']} | Expires at #{form['omb_expiration_date']}", "http://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=#{form['icr_reference_number']}"
  end

  def formtastic_field_type(field)
    case field['field_type']
    when "date"
      "date_select"
    when "datetime"
      "datetime_select"
    else
      field['field_type']
    end
  end
end

app/views/sbir_apps/index.html.slim
.container
  .jumbotron
    h1
      | SBIR

    p
      | The Small Business Innovation Research (SBIR) program is a highly competitive program that encourages domestic small businesses to engage in Federal Research/Research and Development for commercialization.
    p
      | You can fill out and submit the SF-424, which is required to apply for most SBIR program solicitations, here on BusinessUSA and save your results for later.

    = link_to "Start the SF-424", new_sbir_app_path, class: "btn btn-primary btn-lg"

app/views/sbir_apps/new.html.slim
container
  h3
    = form_title(@form)
  p
    | This page will contain information about the form, including background information on what you need to fill it, what you'll need to do, if anything, to provide additional verification, and what to do... blah blah
  p
    | This page will then take the user to an HTML form page that they can fill out with their information.  Or maybe that's just part of this page. I like it all being a part of this page.
  p
    | So down here, we will iterate through the form fields and create input fields to fill out the form.

  .col-md-8
    = semantic_form_for "data", url: sbir_apps_path, class: 'form-horizontal'  do |f|
      = f.inputs do
        = f.input :form_id, :as => :hidden, :input_html => { :value => @form['number'] }
        - @form['form_fields'].each do |form_field|
          = form_input(f, form_field)

      = f.actions do
        = f.action :submit, :as => :button, :label => "Submit Form"
  - if @form['omb_control_number']
    p#omb.col-md-8
      small.right
        = omb_info(@form)

app/views/sbir_apps/show.html.slim
.container
  h3
    = form_title(@form)
  p
    | This page will contain information about the form, including background information on what you need to fill it, what you'll need to do, if anything, to provide additional verification, and what to do... blah blah
  p
    | This page will then take the user to an HTML form page that they can fill out with their information.  Or maybe that's just part of this page. I like it all being a part of this page.
  p
    | So down here, we will iterate through the form fields and create input fields to fill out the form.

  .col-md-8
    = semantic_form_for "data", url: sbir_apps_path, class: 'form-horizontal'  do |f|
      = f.inputs do
        = f.input :form_id, :as => :hidden, :input_html => { :value => @form['number'] }
        - @form['form_fields'].each do |form_field|
          = form_input(f, form_field)

      = f.actions do
        = f.action :submit, :as => :button, :label => "Submit Form"
  - if @form['omb_control_number']
    p#omb.col-md-8
      small.right
        = omb_info(@form)