config/routes.rb
require 'api_constraints'

Mybusa::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :opportunities, :only => [:index, :show]
  get 'find-opportunities', to: 'opportunities#index', as: :find_opportunities

  resources :sbir_solicitations do
    get 'prepopulate', to: 'sbir_solicitations#prepopulate', as: :prepopulate
  end

  resource :profile do
    resources :profile_people, as: 'people'
  end

  resources :sbir_apps

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # API
  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
    	get '/index' => 'base#index'
      resources :profiles
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
    	@profile = current_user.profile || Profile.new
    else
    	@profile = Profile.new
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
- if user_signed_in? and @profile.persisted?
	= render 'profiles/detail'
- elsif user_signed_in? and !@profile.persisted? # No profile, display marketing text
	.row
		.col-md-12
			.full-login-box
				.login
					h2 
						| Start your BusinessUSA profile...
					ul
						li
							| Create a business profile and share it only when <strong>you</strong> want
						li
							| Get personalized search results, tailored to your business
						li
							| Find and submit grant applications <strong>online</strong>
						li
							| New <a href="#">features and services</a> coming soon...
					p
						= link_to("Start my profile", new_profile_path)

- else
	.row
		.col-md-12
			.full-login-box
				.login
					h2 
						| Unleash the power of BusinessUSA...
					ul
						li
							| Create a business profile and share it only when <strong>you</strong> want
						li
							| Get personalized search results, tailored to your business
						li
							| Find and submit grant applications <strong>online</strong>
						li
							| New <a href="#">features and services</a> coming soon...
					p
						a href="#{signin_path}" class="login-shield"
							= image_tag('shield.png')
							span
								| Log in with MyUSA