config/routes.rb
require 'api_constraints'

Mybusa::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)

  resources :opportunities, :only => [:index, :show]
  get 'find-opportunities', to: 'opportunities#index', as: :find_opportunities

  resources :sbir_solicitations do
    get 'prepopulate', to: 'sbir_solicitations#prepopulate', as: :prepopulate
  end

  resource :profile do
    resources :profile_people, as: 'people'
  end

  resources :sbir_apps

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # API
  namespace :api, :defaults => {:format => :json} do
    scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
    	get '/index' => 'base#index'
      resources :profiles
    end
  end
end

app/views/layouts/_businessusa_nav.html.slim
ul.nav.navbar-nav
	li
		= link_to "Tour", "http://business.usa.gov/tour"
	li 
		= link_to "Resources", "http://business.usa.gov/find-resources"
	li
		= link_to "Events", "http://business.usa.gov/events"
	li
		= link_to "About Us", "http://business.usa.gov/about-us"
	li
		= link_to "Contact Us", "http://help.business.usa.gov"
	

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_my_nav.html.slim
ul class="subnav"
  - if user_signed_in?
    - if current_user.has_role? :super_admin or current_user.has_role? :agency_admin
      li
        = link_to 'Admin', admin_users_path
    li
      = link_to 'Logout', signout_path
    li
      = link_to 'Profile', profile_path
    li
      = link_to(image_tag(gravatar_url(current_user), :class => 'avatar'), profile_path, :class => 'avatar-link')
  - else
    li
      = link_to 'Login', signin_path

app/views/layouts/_navigation.html.slim
.row
  .col-md-4
    .branding.clearfix.navbar-header
      - if user_signed_in?
        hgroup.say-my
          | My
      = link_to '<span class="hidden-offscreen">BusinessUSA</span>', root_path, :class => 'navbar-brand'
      hgroup.slogan
        = link_to "Discover. Connect. Grow.", root_path
  .col-md-8
    .share-links
      ul
        li#twitter
          a href="https://twitter.com/bizusa" target="_blank"
        li#linkedIn
          a href="http://www.linkedin.com/groups/BusinessUSA-2521449" target="_blank"
    = render "layouts/my_nav"
    = render "layouts/businessusa_nav"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      title= content_for?(:title) ? yield(:title) : "BusinessUSA"
      meta content=(content_for?(:description) ? yield(:description) : "BusinessUSA") name="description" 
        = stylesheet_link_tag "application", media: "all"
        = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Bitter:400,700"
        = javascript_include_tag "application"
        = include_gon(init: true)
        = analytics_init if Rails.env.production?
        = csrf_meta_tags
        = yield(:head)
        <!--[if lt IE 9]>
        <script src="assets/javascripts/html5shiv.js"></script>
        <![endif]-->
  body class=("#{controller_name} #{action_name} #{user_signed_in? ? "user-signed-in" : ""}")
    #beta
    .navbar.navbar-static-top
      nav#header.navbar-inner
        .container
          = render 'layouts/navigation'
    #main role="main" 
      .container
        .row
          .col-md-12
            = render 'layouts/messages'
        .content
          .row
            .col-md-12
              = yield
      /! ! end of .container
    /! ! end of #main
    footer
      .row
        .container
          .col-md-12
            ul.footer-nav
              li
                = link_to "Home", root_url
              li
                = link_to "About Us", "http://business.usa.gov/about-us"
              li
                = link_to "USA.gov", "http://www.usa.gov"
              li
                = link_to "Privacy and Security", "http://business.usa.gov/privacy-and-security"
              li
                = link_to "API", "http://http://business.usa.gov/apis"
              li
                = link_to "Link to Us", "http://business.usa.gov/link-to-us"
              li
                = link_to "Blogs", "http://business.usa.gov/blog"
              li
                = link_to "Share", "http://www.addthis.com/bookmark.php"
              li
                = link_to "Site Map", "http://business.usa.gov/sitemap"
      .row
        .container
          .col-md-6.center
            .disclaimer
              p
                = image_tag('usflag.png')
                | My.Business.USA.gov might one day be an official website of the U.S. Government.
  = yield(:footer)

app/views/layouts/sbir_solicitations.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      title= content_for?(:title) ? yield(:title) : "BusinessUSA"
      meta content=(content_for?(:description) ? yield(:description) : "BusinessUSA") name="description" 
        = stylesheet_link_tag "application", media: "all"
        = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Bitter:400,700"
        = javascript_include_tag "application"
        = include_gon(init: true)
        = analytics_init if Rails.env.production?
        = csrf_meta_tags
        = yield(:head)
        <!--[if lt IE 9]>
        <script src="assets/javascripts/html5shiv.js"></script>
        <![endif]-->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.min.js"></script>
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .container.droppedHover
        .navbar-header
          button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand[href="#"]
            | FBOpen
    #main role="main" 
      .container
        .row
          .span12
            = render 'layouts/messages'
        .content
          .row
            .span12
              = yield
      /! ! end of .container
    /! ! end of #main